### ISSUE TITLE
[Feature Request] add keyboard shortcut to generate alias

### ISSUE THREAD

**Issue by emhl** [anonaddy/browser-extension#49] opened 2024-01-22 00:39 UTC
generating new aliases takes a lot of clicks. and can be quite tedious if you want to change the email of for all of your accounts. it would be nice to have a keyboard shortcut for generating a new alias with default settings and copy it into the clipboard or paste it into the email input field (like many password managers do)

**Comment by willbrowningme** [comment] 2024-05-16 14:31
Thanks for the suggestion, I'll see what I can do.

Closing as this is a duplicate of #20.

**Closed by willbrowningme** 2024-05-16 14:31 UTC
